development: &defaults
  adapter      : postgresql
  encoding     : unicode
  pool         : 5
  host         : 127.0.0.1
  min_messages : WARNING
  database     : tcbl 

test:
  <<: *defaults

production:
  <<: *defaults
  database : <%= ENV['DB_NAME'] %>
  username : <%= ENV['DB_USERNAME'] %>
  password : <%= ENV['DB_PASSWORD'] %>
  host     : <%= ENV['DB_HOST'] %>
